version: '3.9'

services:
  appserver:
    container_name: wildberries-api-statistics
    #    build:
    #      context: ./wildberries-api-statistics/
    #      dockerfile: ./Dockerfile
    image: ctacshamsheev/wildberries-api-statistics:v1.0
    restart: always
    ports:
      - '80:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wildberries_api_v1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      WILDBERRIES_STATISTICS_AUTH_TOKEN: 'auth_token'
      LOGGING_LEVEL_COM_SHAMSHEEV: INFO

  postgres:
    container_name: postgres
    image: postgres:13.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wildberries_api_v1
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.8
    restart: always
    ports:
      - '5050:5050'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    depends_on:
      - postgres
    links:
      - postgres:pgsql-server
    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres-data: { }