server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        show_sql: false
        ddl-auto: none
      generate-ddl: false
  datasource:
    driverClassName: 'org.postgresql.Driver'
    username: 'postgres'
    password: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/db'

wildberries:
  statistics:
    url: 'https://statistics-api.wildberries.ru/'
    auth:
      token: 'auth_token'
    orders:
      startDate: '2022-01-01T00:00:00.0'
      cron:
        enabled: true
        value: '0 0,30 * * * *'
    sales:
      startDate: '2022-01-01T00:00:00.0'
      cron:
        enabled: true
        value: '0 15,45 * * * *'
    report:
      startDate: '2022-01-01T00:00:00.0'
      cron:
        enabled: false
        value: '0 0 4 * * *'
    incomes:
      startDate: '2022-01-01T00:00:00.0'
      cron:
        enabled: true
        value: '0 7,37 * * * *'
    stocks:
      startDate: '2022-01-01T00:00:00.0'
      cron:
        enabled: true
        value: '0 22,52 * * * *'
timezone: 4

logging:
  level:
    com:
      shamsheev: DEBUG
    org:
      springframework:
        web: DEBUG