create TABLE IF NOT EXISTS order_table
(
    sr_id               varchar(255) not null,
    order_date          timestamp,
    last_change_date    timestamp,
    warehouse_name      varchar(255),
    country_name        varchar(255),
    oblast_name         varchar(255),
    region_name         varchar(255),
    product_id          varchar(255),
    income_id           integer,
    is_supply           boolean,
    is_realization      boolean,
    total_price         numeric(19, 2),
    discount_percent    integer,
    sale_price          numeric(19, 2),
    finish_price        numeric(19, 2),
    price_with_discount numeric(19, 2),
    is_cancel           boolean,
    cancel_date         timestamp,
    order_type          varchar(255),
    sticker             varchar(255),
    g_number            varchar(255),
    primary key (sr_id),
    CONSTRAINT FK_order_product_id FOREIGN KEY (product_id) REFERENCES product_table (id)
);